version: '2'
services:
  web:
    build: .
    ports:
      - "8000:80"
    links:
      - dbpostgres 
    environment:
      DBURL: sqlite:///MBTA_GTFS.db
      DBURL_NEW: postgresql+psycopg2://pguser:pguser@dbpostgres/pgdb     

  dbpostgres:
    image: postgres
    volumes:
      - ./postgresql:/var/lib/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
      POSTGRES_DB: pgdb
